version: "3"

services:
  MS2pg:
    image: postgres:alpine
    ports:
      - "5436:5432"
    container_name: "ms2"
    restart: always
    volumes:
      - ms2pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
volumes:
  ms2pg-data:
